### ISSUE TITLE
SurveyAgeAtLen.fn errors

### ISSUE THREAD

**Issue by okenk** [pfmc-assessments/nwfscSurvey#114]
I am having some trouble running the `SurveyAgeAtLen.fn` function.
 
First, there were age data for a tow ID that was not in the catch data frame. This was a headache to track down, and I wonder if we could add a check for this in the future. (The error occurred in the first for loop.) 

I removed those individuals from the bio data frame and tried again, but got a new error that I have not solved. There are two lines that have similar problems:
```
  outF$nSamps <- getn.f
  outM$nSamps <- getn.m
```
The number of rows in the `outF` (418) and `outM` (384) data frames is not equal to the number of elements in `getn.f` (419) and `getn.m` (386). The code for the `getn` vectors made sense. The `out` data frames are based on `AsF` and `AsM`, and that code was a bit complicated to follow-- my guess is the error is being caused somewhere in this. The equivalent line for unsexed individuals ran fine. In this case, unlike the male and female cases, no rows were filtered out using the `indZero` line.

Here is a minimally reproducible example:
```
wcgbts_catch <- nwfscSurvey::PullCatch.fn(Name = 'canary rockfish', 
                                          SurveyName = 'NWFSC.Combo',
                                          SaveFile = FALSE) 

wcgbts_bio <- nwfscSurvey::PullBio.fn(Name = 'canary rockfish', 
                                      SurveyName = 'NWFSC.Combo',
                                      SaveFile = FALSE)

strata <- nwfscSurvey::CreateStrataDF.fn(
  names = c("shallow_s", "deep_s", "shallow_n", "deep_n"), 
  depths.shallow = c( 55,   183,  55,   183),
  depths.deep    = c(183,   350,  183,  350),
  lats.south     = c( 32,   32,   34.5, 34.5),
  lats.north     = c( 34.5, 34.5, 49,   49))

wcgbts_bio <- dplyr::filter(wcgbts_bio, Trawl_id != '202103010023')

caal <- nwfscSurvey::SurveyAgeAtLen.fn(dir = getwd(), 
                                       datAL = wcgbts_bio, datTows = wcgbts_catch, 
                                       strat.df = strata, ageBins = 1:35,
                                       lgthBins = seq(12, 66, by = 2),
                                       raw = FALSE)
```

**Comment by chantelwetzel-noaa** [comment]
@okenk thank you for reporting these issues.  The unmatchable tow id in the biological data file is a rare issue that I think I have only encountered once before.  We could build in checks for this type of issue, but I would want to think carefully how to do that in a way that a user doesn't just move forward having the check fix the issue rather than reporting this issue to the data team to fix.  I will reach out to the data team to report this issue and inquire how they want similar issue reported in the future.  

The second issue you are encountering is due to a mismatch in dimensions between the processed sex-specific CAAL data and the calculated sample sizes for each year, length bin, and sex.  However, this issue only occurs when `raw = FALSE` is input to the function.  Generally, we opt to not expand the CAAL data (`raw = TRUE`) given there has been concerns around how to appropriately do that. This function includes legacy code that implements an approach on how to expanded these data but I don't think anyone has used this method within an assessment to-date and clearly there is an issue in the code for at least the canary data.  I would recommend not expanding the CAAL data at this time since I may not have the needed time to sort out what is occurring within the expansion function.  Sorry for the issues that this caused.

**Comment by Curt-Whitmire-NOAA** [comment]
@chantelwetzel-noaa @okenk this will take me a bit more time to figure out the fix. I'm scratching my head a bit because there is in fact both canary catch and specimen data associated with this tow, even when using the station_invalid = 0 filter that the R functions as use, as evidenced by using the following URL calls to the API:

*Note that both results show st year_stn_invalid is NULL.

-- For catch
https://www.webapps.nwfsc.noaa.gov/data/api/v1/source/trawl.catch_fact/selection.json?filters=common_name=canary%20rockfish,station_invalid=0,trawl_id=202103010023


-- For specimens
https://www.webapps.nwfsc.noaa.gov/data/api/v1/source/trawl.individual_fact/selection.json?filters=common_name=canary%20rockfish,station_invalid=0,trawl_id=202103010023

I examined the code for both R functions, and as expected they seem to use identical filters, save the ones specific to the source table. For the life of me, I can't figure out why the PullBio fxn includes results from this tow, while the PullCatch fxn does not. I seem to have isolated the issue to the fact that the target station for this tow is valid, but the actual station where the tow occurred is currently marked as invalid (station_invalid != 0). When I set the station_invalid field to 0 for the actual station, both R functions return data for this tow. But that doesn't explain what's going on under the hood with the API, and that's where I still need to dig a bit.

Stay tuned and I hope to have a fix for this soon.
