### ISSUE TITLE
Better document all the wonderful less-frequently-used functions in nwfscSurvey

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pfmc-assessments/nwfscSurvey#42]
I almost spent a long time creating a new map function for this package without realizing that `PlotMap.fn()` was already available.
I just added a note about it to the vignette in commit aed0f490afc6822edbfbdff506d20c4ce35238fd but that doesn't offer much.

Thanks @ericward-noaa for the updates to this function. 

Here's the example for dogfish for those curious what the results look like. 
![CPUE_Map](https://user-images.githubusercontent.com/4992918/114244319-12ab3200-9943-11eb-8679-93a5dbd80a93.png)
![CPUE_Map_Year](https://user-images.githubusercontent.com/4992918/114244320-1343c880-9943-11eb-9a04-fa168ddcfb07.png)

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA thanks for the reminder that the functions should be known about 😄 . This new 🥇 website that @chantelwetzel-noaa created (lists all of the available functions](http://pfmc-assessments.github.io/nwfscSurvey/reference/index.html). We can use the @family feature in the roxygen documentation to increase the visibility of functions and provide groupings. @chantelwetzel-noaa is also working on renaming functions to things like `pull_*()` and `plot_*()` to help users navigate the package. I think we have a better handle on this issue now than we did on April of 2021 so I am going to close it but please feel free to reopen if you disagree.

**Comment by iantaylor-NOAA** [comment]
@chantelwetzel-noaa and @kellijohnson-NOAA, I'm excited by all the improvements that you two have been making to this package. The new page is a great resource and definitely satisfies the need I opened this issue to address.

**Comment by brianlangseth-NOAA** [comment]
I hope @chantelwetzel-noaa work with renaming functions will resolve this but there are a number of seemingly duplicated functions in the list. For example there are functions
pull_bio
PullBio.fn
pull_biological_samples

The first two seem to produce the same data, while the third appears to be different biological data from the first two. If old functions will be kept (I assume PullBio.fn is old), can it be clear that these are legacy, and which new functions are meant to replace then?

**Comment by chantelwetzel-noaa** [comment]
The `pull_bio` and the `PullBio.fn` do the same task of pulling biological data (lengths, ages, weights) from the data warehouse. The `pull_bio` function will eventually be the successor and the `PullBio.fn` will be deprecated. The development of the new function was done separately since there were fairly major changes being made and this approach ensures that the new approach does not break existing workflows. The `pull_biological_samples` function pulls detailed information for biological collections by the survey that are then processed later in lab (e.g., maturity, fecundity, fin clips). This functions provides the sample numbers which allows the samples to then be linked back to a fish.  I did struggle a bit when trying to create a name for this new function that provided a clear summary of its purpose but I did include a brief description of what it does in the function documentation.
