### ISSUE TITLE
Add length/age frequency figures similar to those created by r4ss

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [pfmc-assessments/nwfscSurvey#55]
It would be used to visualize the length and age composition data by year similar to the data figures provided by r4ss.  Adding this type of data visualization can identify issues with the composition data expansion before putting data into the model.
![comp_lendat_flt2mkt0_page1](https://user-images.githubusercontent.com/6172110/137191878-dbd947d9-a933-4c71-a331-4183ada63e07.png)
l

**Comment by iantaylor-NOAA** [comment]
I like this idea, including the "similar to" element since the r4ss plot depends on many layers of old code and would not be easy to adapt to `nwfscSurvey` data even if `nwfscSurvey` depended on r4ss (which probably isn't a good idea anyway). 
I would suggest having one of the resident ggplot users come up with something new and better.

**Comment by chantelwetzel-noaa** [comment]
Commit 00a949b83c00a252dae0feb2cc31e411bcece124 adds the below composition plotting within the new `plot_comps` function. 

![sexed_length_r4ss_frequency_sex_F_M](https://user-images.githubusercontent.com/6172110/205085103-9cf827ac-529b-4eed-9cf5-59f961f1a103.png)

I am going to close this issue for now but if needed revisions to this figure are identified this can be reopened.
